spring:
  application:
    name: redis
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456
    database: 15
    connect-timeout: 2000 # 最大连接超时时间
    lettuce:
      pool:
        max-active: 8 # 最大连接数
        max-idle: 8 # 最大空闲连接数
        max-wait: 3000 # 最大等待超时时间
        min-idle: 0 # 最小空闲连接数

